/*
 * Ninja Slushi recipe dataset.
 *
 * Curated from ../references/official-recipes.md, ../references/recipes.md
 * and ../references/community-recipes.md.
 *
 * Each recipe:
 *   id           unique slug
 *   name         display name
 *   preset       one of SLUSH | SPIKED SLUSH | FROZEN JUICE | MILKSHAKE | FRAPPE
 *   source       "official" (Ninja Inspiration Guide) or "community" (r/ninjaslushi)
 *   tags         array drawn from CATEGORY_TAGS below — a recipe can have several
 *   difficulty   "easy" | "medium" | "advanced" (see computeDifficulty() in app.js
 *                for the rule; a few recipes pin it explicitly via `difficultyOverride`
 *                when ingredient count alone would understate the effort, e.g. a
 *                gelatin-stabilized frosé)
 * kid           optional, true for kid-friendly recipes
 *   ingredients  array of free-text "qty + ingredient" strings (this is what the
 *                sugar-free rewriter in app.js pattern-matches against)
 *   directions   short prep/run notes
 *   sugarFreeNote  optional recipe-specific note shown in sugar-free mode, in
 *                addition to the automatic per-ingredient rewrite
 *   url          optional source link (community recipes only)
 */

const CATEGORY_TAGS = [
  "creamy", "milkshake", "refreshing", "fruity", "spicy",
  "tropical", "citrus", "coffee", "chocolate", "cocktail", "mocktail",
];

const RECIPES = [
  // ---------- SLUSH ----------
  {
    id: "one-ingredient-soda-slush",
    name: "One-Ingredient Soda Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: ["2–5 (355 ml) cans any regular full-sugar soda"],
    directions: "Pour soda into the vessel. Run SLUSH (~3 bars). Diet/sugar-free soda will not work on its own.",
    sugarFreeNote: "Diet soda alone will not freeze. Use a diet/zero-sugar soda and add ~15–22 ml liquid allulose (or ~12–18 g granulated) per 355 ml can to restore the sugar the machine needs.",
  },
  {
    id: "pink-lemonade-slush",
    name: "Pink Lemonade Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "citrus"],
    ingredients: ["660 ml–1.76 L water", "45–105 g pink lemonade powder mix"],
    directions: "Whisk powder into water until fully dissolved, pour in, run SLUSH.",
  },
  {
    id: "sodas-that-just-work",
    name: "Classic Soda Slush (Coke / Root Beer / Fanta / Pepsi / Mountain Dew)",
    preset: "SLUSH",
    source: "community",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: ["1.9 L any full-sugar soda (Coke, root beer, strawberry Fanta, cherry Coke, Pepsi, Mountain Dew, Jarritos)"],
    directions: "Run SLUSH at ~3 bars. More flavorful sodas work better — freezing mutes flavor. Avoid beer.",
  },
  {
    id: "cherry-icee-copycat",
    name: "Cherry Icee Copycat",
    preset: "SLUSH",
    source: "community",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: ["3 parts full-sugar Sprite", "1 part Hawaiian Shaved Ice Classic Cherry syrup"],
    directions: "Mix and run SLUSH. Must use full-sugar Sprite, not Zero.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hnpzto/getting_closer_to_a_cherry_icee/",
  },
  {
    id: "icee-from-syrup",
    name: "Icee From Syrup",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing", "fruity"],
    ingredients: ["180 ml Icee syrup (≈22 g sugar)", "840 ml water"],
    directions: "Low sugar (~2%) — run SLUSH +2 to +3 bars for a proper thick slush.",
  },
  {
    id: "orange-creamsicle",
    name: "Orange Creamsicle Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["creamy", "fruity", "citrus"],
    ingredients: ["2 L orange soda", "dash vanilla extract", "½ can sweetened condensed milk"],
    directions: "Mix and run SLUSH. Tastes like a Creamsicle.",
  },
  {
    id: "pink-starburst-slush",
    name: "Pink Starburst Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["creamy", "fruity"],
    ingredients: ["1 bottle Simply Watermelon juice", "½ can sweetened condensed milk"],
    directions: "Mix well before pouring in. Run SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jbhaf3/pink_starburst_slush/",
  },
  {
    id: "triple-dr-pepper",
    name: "Triple Dr Pepper Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing", "fruity"],
    ingredients: ["1 can Dr Pepper Strawberries & Cream", "1 can Dr Pepper Creamy Coconut", "1 can regular Dr Pepper"],
    directions: "Combine all three and run SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1igvgj5/my_favourite_slush/",
  },
  {
    id: "orange-julius",
    name: "Orange Julius Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["creamy", "citrus", "fruity"],
    ingredients: ["1.44 L orange juice (no pulp)", "480 ml 2% milk", "15 ml vanilla extract", "~200 g granulated sugar (or allulose)"],
    directions: "Whisk, pour in, run SLUSH at 6 bars.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hsfbgx/orange_julius/",
  },
  {
    id: "zevia-allulose-slush",
    name: "Sugar-Free Zevia Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing"],
    ingredients: ["1 can Zevia (unsweetened soda)", "~22 ml liquid allulose per can", "few drops food coloring (optional, Zevia is clear)"],
    directions: "Stir allulose into the Zevia until dissolved, then run SLUSH.",
    sugarFreeNote: "Already the sugar-free reference build — this is what the toggle is emulating for other sodas.",
  },
  {
    id: "coke-zero-slush",
    name: "Sugar-Free Coke Zero Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing"],
    ingredients: ["2 cans Coke Zero", "~50 g Splenda allulose", "~50 g monk fruit-erythritol blend"],
    directions: "Aim for real Coke's ~39 g sugar equivalent. Run SLUSH, maybe +1 bar.",
  },
  {
    id: "half-diet-blend",
    name: "Half-Diet Soda Blend",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing", "fruity"],
    ingredients: ["¼ full-sugar Orange Crush", "¾ Sprite Zero (or ½ regular soda + ½ diet soda)"],
    directions: "Combine and run SLUSH — slushes fine with reduced total sugar.",
  },

  // ---------- FROZEN JUICE ----------
  {
    id: "cranberry-lime-slush",
    name: "Cranberry Lime Slush",
    preset: "FROZEN JUICE",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "citrus"],
    ingredients: ["560 ml–1.38 L cranberry juice", "160–360 ml limeade"],
    directions: "Pour both in and run FROZEN JUICE.",
  },
  {
    id: "tropical-juice-slush",
    name: "Tropical Juice Slush",
    preset: "FROZEN JUICE",
    source: "official",
    kid: true,
    tags: ["tropical", "fruity", "refreshing"],
    ingredients: ["720 ml–1.8 L tropical juice blend"],
    directions: "Pour in and run FROZEN JUICE.",
  },
  {
    id: "straight-single-juices",
    name: "Straight Single-Juice Slush (Mango / Lemonade / Fruit Punch)",
    preset: "FROZEN JUICE",
    source: "community",
    kid: true,
    tags: ["fruity", "refreshing", "tropical"],
    ingredients: ["1.9 L single juice: Snapple Mango Madness, Simply Lemonade, Snapple Fruit Punch, orange juice, or apple cider"],
    directions: "Run FROZEN JUICE (or SLUSH) at a low bar. Tart/low-sugar juices may need added sugar. Apple juice (Mott's) needs +2 bars.",
  },
  {
    id: "caramel-apple-slush",
    name: "Caramel Apple Slush",
    preset: "FROZEN JUICE",
    source: "community",
    kid: true,
    tags: ["fruity", "creamy"],
    ingredients: ["1.9 L apple cider", "caramel syrup (for swirl)", "whipped cream + cinnamon (topping)"],
    directions: "Run apple cider on FROZEN JUICE at 2 bars; swirl the glass with caramel syrup, top with whipped cream and cinnamon.",
  },
  {
    id: "fall-pumpkin-cider-kids",
    name: "Fall Pumpkin Cider (Kids)",
    preset: "FROZEN JUICE",
    source: "community",
    kid: true,
    tags: ["spicy", "fruity"],
    ingredients: ["2 L apple cider", "½ can (of 425 g) pumpkin purée", "50 g brown sugar", "50 g white sugar", "~2 g pumpkin pie spice", "5 ml vanilla extract"],
    directions: "Whisk pumpkin purée and spices into cider, then run FROZEN JUICE.",
  },
  {
    id: "lemonade-cranberry-mocktail",
    name: "Non-Alcoholic Lemonade-Cranberry Slush",
    preset: "FROZEN JUICE",
    source: "community",
    tags: ["mocktail", "citrus", "refreshing"],
    ingredients: ["480 ml lemonade", "240 ml cranberry juice", "splash simple syrup"],
    directions: "Mix and run FROZEN JUICE/SLUSH. Add 120 ml vodka for the adult version.",
  },

  // ---------- MILKSHAKE ----------
  {
    id: "vanilla-milkshake",
    name: "Vanilla Milkshake",
    preset: "MILKSHAKE",
    source: "official",
    kid: true,
    tags: ["creamy", "milkshake"],
    ingredients: ["600 ml–1.38 L whole milk", "120–270 ml heavy cream", "100–250 g granulated sugar", "15–40 ml vanilla extract"],
    directions: "Whisk to combine, pour in (720 ml min), run MILKSHAKE. Dispense within 30 minutes.",
  },
  {
    id: "chocolate-milkshake",
    name: "Chocolate Milkshake",
    preset: "MILKSHAKE",
    source: "official",
    kid: true,
    tags: ["creamy", "milkshake", "chocolate"],
    ingredients: ["480 ml–1.04 L whole milk", "240–560 ml heavy cream", "5–15 ml vanilla extract", "24–65 g granulated sugar", "60–160 ml chocolate syrup", "10–43 g cocoa powder"],
    directions: "Whisk until sugar/syrup/cocoa fully dissolved, pour in, run MILKSHAKE. Optional: whipped cream, chocolate sauce.",
  },
  {
    id: "wendys-frosty-copycat",
    name: "Wendy's Frosty Copycat",
    preset: "MILKSHAKE",
    source: "community",
    kid: true,
    tags: ["creamy", "milkshake", "chocolate"],
    ingredients: ["1.2 L 2% chocolate milk", "1 can (420 ml) sweetened condensed milk", "¾ container Cool Whip"],
    directions: "Whisk together first, then run MILKSHAKE +1 to +2 bars. Full 1.9 L batch ≈ 40 min.",
    url: "https://reddit.com/r/ninjaslushi/comments/1h8vw9q/ninja_slush_recipes_ongoing_list/",
  },
  {
    id: "halo-top-chocolate-shake",
    name: "Halo Top Chocolate Shake (Low-Cal)",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake", "chocolate"],
    ingredients: ["2 tubs (480 ml each) Halo Top chocolate, melted", "240 ml whole milk", "120 ml zero-sugar Cool Whip"],
    directions: "Melt Halo Top, whisk everything together, run MILKSHAKE. Add Bailey's for a low-cal mudslide.",
    url: "https://reddit.com/r/ninjaslushi/comments/1k0um84/halo_top_milkshake/",
  },
  {
    id: "protein-frosty",
    name: "Protein \"Frosty\"",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake", "chocolate"],
    ingredients: ["960 ml chocolate milk", "960 ml lactose-free milk", "1 packet Carnation Instant Breakfast", "120 ml sweetened condensed milk", "whipped cream (3-sec squirt, for fluff)"],
    directions: "Whisk together and run MILKSHAKE.",
  },
  {
    id: "strawberry-milkshake",
    name: "Strawberry Milkshake",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake", "fruity"],
    ingredients: ["800 ml milk", "50 ml strawberry syrup", "1.5 capfuls vanilla extract", "100 ml double cream", "200 ml sweetened condensed milk"],
    directions: "Whisk to combine, run MILKSHAKE. Halve the sweetener for less-sweet US palates.",
    url: "https://reddit.com/r/ninjaslushi/comments/1h45jvt/just_made_my_first_strawberry_milkshake/",
    difficultyOverride: "medium",
  },
  {
    id: "creme-brulee-milkshake",
    name: "Crème Brûlée Milkshake",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake"],
    ingredients: ["600 ml whole milk", "100 ml heavy cream", "120 ml+ Monin crème brûlée syrup"],
    directions: "Whisk together, run MILKSHAKE.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jkhws1/milkshake_go%C3%BBt_cr%C3%A8me_br%C3%BBl%C3%A9e/",
  },
  {
    id: "dole-whip-from-mix",
    name: "Dole Whip (From Mix)",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake", "tropical", "fruity"],
    ingredients: ["~120 g Dole Whip mix (check package)", "960 ml cold water", "splash heavy whipping cream (optional)"],
    directions: "Whisk mix into water, run MILKSHAKE +1.",
    url: "https://reddit.com/r/ninjaslushi/comments/1ka00cw/dole_whip/",
  },
  {
    id: "dole-whip-from-scratch",
    name: "Dole Whip Shake (From Scratch)",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake", "tropical", "fruity"],
    ingredients: ["2×180 ml pineapple juice", "2 ripe bananas", "1 can coconut milk", "~8 g powdered sugar", "15 ml lime juice"],
    directions: "Blend the fruit first, then run MILKSHAKE. Makes ~1.4 L.",
    difficultyOverride: "advanced",
  },
  {
    id: "dairy-free-pb-shake",
    name: "Dairy-Free Peanut Butter Shake",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake"],
    ingredients: ["oat milk", "plant-based heavy cream", "sugar (to taste)", "PB2 powder", "a little peanut-butter syrup"],
    directions: "Amounts are vague in the source — use as a template and adjust to taste. Run MILKSHAKE.",
  },

  // ---------- FRAPPE ----------
  {
    id: "coffee-frappe",
    name: "Coffee Frappé",
    preset: "FRAPPE",
    source: "official",
    tags: ["coffee", "creamy"],
    ingredients: ["240–540 ml half & half", "480 ml–1.08 L black coffee", "5–15 ml vanilla extract", "65–150 g granulated sugar"],
    directions: "Whisk to combine, pour in (720 ml min), run FRAPPÉ. Dispense within 30 minutes.",
  },
  {
    id: "caramel-frappe",
    name: "Caramel Frappé",
    preset: "FRAPPE",
    source: "official",
    tags: ["coffee", "creamy"],
    ingredients: ["240–540 ml half & half", "480 ml–1.08 L black coffee", "80–180 ml caramel sauce"],
    directions: "Whisk, pour in, run FRAPPÉ. Swap caramel sauce for chocolate sauce for a Mocha Frappé.",
    tagsExtra: ["chocolate"],
  },
  {
    id: "starbucks-bottle-frappe",
    name: "Vanilla-Caramel Frappé (Bottled Starbucks)",
    preset: "FRAPPE",
    source: "community",
    tags: ["coffee", "creamy"],
    ingredients: ["480 ml Vanilla Starbucks Frappuccino", "180 ml Caramel Starbucks Frappuccino", "30 ml heavy whipping cream"],
    directions: "Combine and run FRAPPÉ at 3 bars, ~20 min. Rim with caramel + Biscoff for a treat.",
    url: "https://reddit.com/r/ninjaslushi/comments/1i66579/vanilla_caramel_frapp%C3%A9_with_a_chocolate_and/",
  },
  {
    id: "caramel-frap-from-scratch",
    name: "Caramel Frap (From Scratch)",
    preset: "FRAPPE",
    source: "community",
    tags: ["coffee", "creamy"],
    ingredients: ["720 ml chilled black coffee", "720 ml chilled whole milk", "60 ml heavy cream", "200 g caster sugar"],
    directions: "Whisk until sugar dissolves. Run FRAPPÉ, ~40 min. Line the cup with caramel sauce.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jjvqtg/made_the_wife_a_caramel_frap_today_and/",
  },
  {
    id: "low-cal-nondairy-coffee-frappe",
    name: "Low-Cal Non-Dairy Coffee Frappé",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["coffee"],
    ingredients: ["660 ml coffee", "15 ml vanilla extract", "~96 g granular allulose", "900 ml unsweetened almond milk"],
    directions: "Whisk together and run on MILKSHAKE (not FRAPPÉ). Icy due to no dairy, but tasty.",
    url: "https://reddit.com/r/ninjaslushi/comments/1k8p4an/coffee_frappe_low_cal_nondairy/",
    sugarFreeNote: "Already built with allulose — the reference build for the sugar-free toggle.",
  },
  {
    id: "iced-capp",
    name: "Iced Capp",
    preset: "FRAPPE",
    source: "community",
    tags: ["coffee", "creamy"],
    ingredients: ["480 ml hot water", "~8 g instant coffee", "240 ml 10% cream (half-and-half)", "50 g granulated sugar", "5 ml vanilla extract"],
    directions: "Dissolve coffee/sugar in the hot water, cool, add cream + vanilla. Run FRAPPÉ −1 bar, ready in 10–15 min.",
  },

  // ---------- SPIKED SLUSH ----------
  {
    id: "frozen-mimosa",
    name: "Frozen Mimosa",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "fruity", "citrus"],
    ingredients: ["300–800 ml orange juice", "420 ml–1.12 L sparkling wine / Champagne / Prosecco / Cava"],
    directions: "Pour both in, run SPIKED SLUSH. Mocktail: swap sparkling wine for sparkling white grape juice/cider, run SLUSH at 8 bars.",
    tagsMocktail: true,
  },
  {
    id: "coconut-lime-daiquiri",
    name: "Coconut Lime Daiquiri",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "tropical", "citrus", "creamy"],
    ingredients: ["300–800 ml unsweetened canned coconut milk", "300–800 ml limeade", "90–240 ml light rum", "juice of 2–4 fresh limes", "36–65 g granulated sugar"],
    directions: "Whisk until coconut milk is emulsified and smooth, pour in, run SPIKED SLUSH. Mocktail: zero-proof rum on SLUSH.",
  },
  {
    id: "frose-official",
    name: "Frosé",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "fruity"],
    ingredients: ["510 ml–1.04 L rosé wine", "270–720 ml white cranberry-strawberry juice", "60–160 ml simple syrup"],
    directions: "Combine, run SPIKED SLUSH at 8 bars. Optional garnish: strawberries.",
  },
  {
    id: "red-sangria",
    name: "Red Sangria",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "fruity", "citrus"],
    ingredients: ["300–780 ml red wine", "40–120 ml orange liqueur or brandy", "360–900 ml orange juice", "18–50 g light brown sugar"],
    directions: "Combine, run SPIKED SLUSH. Optional garnish: orange slices.",
  },
  {
    id: "frozen-mango-margarita",
    name: "Frozen Mango Margarita",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "fruity", "tropical", "citrus"],
    ingredients: ["480 ml–1.2 L mango margarita mix", "80–180 ml water", "80–180 ml lime juice", "80–180 ml tequila"],
    directions: "Pour all in, run SPIKED SLUSH. Mocktail: swap tequila for zero-proof tequila, run SLUSH at 5 bars.",
  },
  {
    id: "cinco-de-mayo-grapefruit-marg",
    name: "Cinco de Mayo Grapefruit Margarita",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "citrus", "fruity"],
    ingredients: ["360 ml reposado tequila", "960 ml margarita mix", "300 ml fresh grapefruit juice", "120 ml fresh lime juice", "360 ml water"],
    directions: "Combine, run SPIKED SLUSH at 10 bars. A Chambord floater on top is a nice touch.",
    url: "https://reddit.com/r/ninjaslushi/comments/1kfhntm/in_honor_of_cinco_de_mayo/",
  },
  {
    id: "skinny-margarita-allulose",
    name: "Skinny Margarita (Allulose)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "citrus"],
    ingredients: ["192 ml fresh lime juice", "280 ml blanco tequila", "152 ml Cointreau", "46 ml liquid allulose", "710 ml water"],
    directions: "Combine, run SPIKED SLUSH +1 bar. Nearly fills the larger tank.",
    url: "https://reddit.com/r/ninjaslushi/comments/1i8znfj/low_cal_pink_cadillac_marg/",
    sugarFreeNote: "Already built with allulose — no conversion needed.",
  },
  {
    id: "pina-colada-spiked",
    name: "Piña Colada (Spiked)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "tropical", "creamy"],
    ingredients: ["540 ml pineapple (3 small cans)", "1 small can (120 ml) cream of coconut", "150 ml sweetened condensed milk", "30 ml lime juice", "115 ml dark rum"],
    directions: "Refrigerate ingredients first, then run SPIKED SLUSH. Adjust sweetness before pouring in.",
    url: "https://reddit.com/r/ninjaslushi/comments/1esnato/pina_colada/",
  },
  {
    id: "painkiller",
    name: "Painkiller",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "tropical", "spicy"],
    ingredients: ["600 ml pineapple juice", "300 ml orange juice", "300–360 ml cream of coconut (microwaved 60 s to liquefy)", "180–480 ml Myers/navy-strength rum", "grated nutmeg (topping)"],
    directions: "Combine, run SPIKED SLUSH at the coldest setting. Add water if too thin; grate nutmeg on top.",
    url: "https://reddit.com/r/ninjaslushi/comments/1j0g7ci/what_setting_for_a_mudslide/",
  },
  {
    id: "bushwacker",
    name: "Bushwacker (Flora-Bama Copycat)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "creamy", "chocolate", "tropical"],
    ingredients: ["120 ml Cruzan aged dark rum", "120 ml vodka", "120 ml Amaretto", "120 ml Irish cream", "120 ml Kahlúa", "120 ml crème de cacao", "120 ml cream of coconut", "480 ml Fairlife 2% milk", "240 ml water"],
    directions: "Pre-mix minus the cream of coconut and freeze for a party; add cream of coconut per refill. Run SPIKED SLUSH.",
    difficultyOverride: "advanced",
  },
  {
    id: "paralyzer",
    name: "Paralyzer",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "creamy", "chocolate"],
    ingredients: ["720 ml milk", "1 can cola", "120 ml vodka", "180 ml Kahlúa"],
    directions: "Combine, run SPIKED SLUSH ~25 min. Tip: swap milk for water + 18% cream for a lighter-yet-richer result.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hq1c26/paralyzer_slush/",
  },
  {
    id: "ninja-hummer",
    name: "Ninja Hummer",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "creamy", "chocolate"],
    ingredients: ["960 ml heavy cream", "480 ml milk", "180 ml vodka", "180 ml Mr. Black (or Kahlúa)", "200 g granulated sugar"],
    directions: "Combine, run SPIKED SLUSH. Top with whipped cream + dark chocolate syrup.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hs3jj6/ninja_hummer/",
  },
  {
    id: "boozy-eggnog-milkshake",
    name: "Boozy Eggnog Milkshake",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "creamy", "spicy"],
    ingredients: ["960 ml eggnog", "60 ml water", "240 ml whole milk", "360 ml Irish whiskey"],
    directions: "Combine and run SPIKED SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hre0zo/boozy_egg_nog_milkshake/",
  },
  {
    id: "hard-cider-slush",
    name: "Hard Cider Slush",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "spicy", "fruity"],
    ingredients: ["1.44 L real apple cider (not juice)", "4 shots Bulleit bourbon (or Crown Royal)"],
    directions: "Combine and run SPIKED SLUSH. Better cider makes a better result.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jnk792/hard_cider_slush/",
  },
  {
    id: "london-mule",
    name: "London Mule",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "citrus", "spicy", "refreshing"],
    ingredients: ["180 ml gin", "60 ml lime juice", "540 ml diet ginger beer", "6 dashes bitters"],
    directions: "Chill and mix first (~30 min), then run SPIKED SLUSH, no adjustments needed.",
    url: "https://reddit.com/r/ninjaslushi/comments/1h8vw9q/ninja_slush_recipes_ongoing_list/",
    sugarFreeNote: "Already uses diet ginger beer — the alcohol acts as the antifreeze here, so no added sugar is needed.",
  },
  {
    id: "frozen-green-tea-shot",
    name: "Frozen Green Tea Shot",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "fruity", "spicy"],
    ingredients: ["240 ml Jameson", "240 ml peach schnapps", "360 ml sour mix", "480 ml Sprite", "water, to fill/adjust"],
    directions: "Combine and run SPIKED SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jdj2np/any_st_patrick_slushy_ideas/",
  },
  {
    id: "liquid-marijuana",
    name: "Liquid Marijuana",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "tropical", "fruity"],
    ingredients: ["60 ml Malibu Black", "60 ml melon liqueur", "60 ml blue curaçao", "60 ml spiced rum", "480 ml pineapple juice", "240 ml 7Up", "360 ml water"],
    directions: "Combine and run SPIKED SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jdj2np/any_st_patrick_slushy_ideas/",
    difficultyOverride: "advanced",
  },
  {
    id: "irish-coffee-frappe",
    name: "Irish Coffee Frappé",
    preset: "FRAPPE",
    source: "community",
    tags: ["cocktail", "coffee", "creamy"],
    ingredients: ["Jameson (to taste)", "espresso (to taste)", "Irish cream (to taste)", "half-and-half (to taste)", "vanilla extract (to taste)", "a little sugar (to taste)"],
    directions: "Amounts to taste — combine and run FRAPPÉ.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jdj2np/any_st_patrick_slushy_ideas/",
  },
  {
    id: "sugar-free-rum-punch",
    name: "Sugar-Free Rum Punch",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "fruity", "refreshing"],
    ingredients: ["1.56 L water", "360 ml Captain Morgan", "Crystal Light fruit punch mix, to the fill line", "a few squirts lime juice"],
    directions: "Combine, run SPIKED SLUSH −1 bar. The alcohol is the antifreeze, so no added sugar is needed.",
    url: "https://reddit.com/r/ninjaslushi/comments/1iwxto6/sugarfree_rum_punch/",
    sugarFreeNote: "Already sugar-free — built around Crystal Light + alcohol as the antifreeze.",
  },
  {
    id: "fall-pumpkin-cider-adult",
    name: "Fall Pumpkin Cider (Adult)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "spicy", "fruity"],
    ingredients: ["2 L apple cider", "½ can (of 425 g) pumpkin purée", "50 g brown sugar", "50 g white sugar", "~2 g pumpkin pie spice", "5 ml vanilla extract", "Fireball whisky, to taste"],
    directions: "Whisk pumpkin/spice into cider, add Fireball to taste, run SPIKED SLUSH.",
  },
  {
    id: "crown-and-coke",
    name: "Crown & Coke (Salt Grass Copycat)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail"],
    ingredients: ["2 cans Coca-Cola (355 ml each)", "120 ml Crown Royal (vanilla Crown chaser optional)"],
    directions: "Combine and run SPIKED SLUSH.",
  },
  {
    id: "boozey-cherry-limeade",
    name: "Boozey Cherry Limeade",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "fruity", "citrus", "refreshing"],
    ingredients: ["240 ml Deep Eddy lime vodka", "240 ml water", "1.44 L cherry 7Up"],
    directions: "Combine and run SPIKED SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hm6ebf/boozey_cherry_limeade/",
  },

  // ---------- Official "Create Your Own" builder charts ----------
  // Expanded from official-recipes.md's builder tables. Near-duplicates of
  // recipes already above (e.g. generic "Whiskey Cola" / "Rum & Cola" vs.
  // the already-encoded Crown & Coke / Spiced Rum & Coke) are intentionally
  // left out.
  {
    id: "frozen-mai-tai-builder",
    name: "Frozen Mai Tai (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "tropical", "fruity"],
    ingredients: [
      "400–780 ml mai tai drink mix (no alcohol)",
      "270–540 ml water (omit and use extra mix instead, for a lower-sugar mix)",
      "60–120 ml white rum + dark rum, split",
    ],
    directions: "Combine mix, water, and both rums; run SPIKED SLUSH. Garnish with lime and cherries.",
  },
  {
    id: "strawberry-daiquiri-builder",
    name: "Strawberry Daiquiri (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "fruity"],
    ingredients: [
      "400–780 ml strawberry daiquiri drink mix (no alcohol)",
      "270–540 ml water (omit and use extra mix instead, for a lower-sugar mix)",
      "60–120 ml white rum",
    ],
    directions: "Combine and run SPIKED SLUSH. Garnish with strawberry and lime.",
  },
  {
    id: "peach-iced-tea-slush",
    name: "Peach Iced Tea Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: ["480 ml–1.2 L sweetened iced tea", "240–660 ml peach nectar"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "pomegranate-iced-tea-slush",
    name: "Pomegranate Iced Tea Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: ["480 ml–1.2 L sweetened iced tea", "240–660 ml pomegranate juice"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "pineapple-iced-tea-slush",
    name: "Pineapple Iced Tea Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "tropical"],
    ingredients: ["480 ml–1.2 L sweetened iced tea", "240–660 ml pineapple juice"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "passion-fruit-iced-tea-slush",
    name: "Passion Fruit Iced Tea Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "tropical"],
    ingredients: ["480 ml–1.2 L sweetened iced tea", "240–660 ml passion fruit nectar"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "mango-iced-tea-slush",
    name: "Mango Iced Tea Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "tropical"],
    ingredients: ["480 ml–1.2 L sweetened iced tea", "240–660 ml mango nectar"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "cranberry-strawberry-lemonade-slush",
    name: "Cranberry-Strawberry Lemonade Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "citrus"],
    ingredients: ["480 ml–1.2 L sweetened lemonade", "240–660 ml cranberry-strawberry juice"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "mango-lemonade-slush",
    name: "Mango Lemonade Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "citrus", "tropical"],
    ingredients: ["480 ml–1.2 L sweetened lemonade", "240–660 ml mango nectar"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "peach-lemonade-slush",
    name: "Peach Lemonade Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "citrus"],
    ingredients: ["480 ml–1.2 L sweetened lemonade", "240–660 ml peach nectar"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "half-and-half-slush",
    name: "Half & Half Slush (Arnold Palmer Style)",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "citrus"],
    ingredients: ["480 ml–1.2 L sweetened lemonade", "240–660 ml sweetened iced tea"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "orange-lemonade-slush",
    name: "Orange Lemonade Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "citrus"],
    ingredients: ["480 ml–1.2 L sweetened lemonade", "240–660 ml orange juice"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "cherry-limeade-slush",
    name: "Cherry Limeade Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "citrus"],
    ingredients: ["480 ml–1.2 L limeade", "240–660 ml cherry juice"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "pomegranate-limeade-slush",
    name: "Pomegranate Limeade Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "citrus"],
    ingredients: ["480 ml–1.2 L limeade", "240–660 ml pomegranate juice"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "party-punch-slush",
    name: "Party Punch Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: ["480 ml–1.2 L lemon-lime soda", "240–660 ml fruit punch"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "cherry-cola-slush",
    name: "Cherry Cola Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: ["480 ml–1.2 L cola", "240–660 ml cherry juice"],
    directions: "Combine both flavors, run SLUSH at 2 bars.",
  },
  {
    id: "cranberry-orange-frozen-juice",
    name: "Cranberry Orange Frozen Juice",
    preset: "FROZEN JUICE",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "citrus"],
    ingredients: ["480 ml–1.2 L orange juice", "240–660 ml cranberry juice"],
    directions: "Combine both juices, run FROZEN JUICE.",
  },
  {
    id: "flavored-syrup-slush-builder",
    name: "Flavored Syrup Slush (Build Your Own)",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: [
      "120–320 ml flavored syrup (blue raspberry, grape, grapefruit, green apple, lime, mango, orange, pineapple, pomegranate, or watermelon)",
      "600 ml–1.56 L water",
    ],
    directions: "Stir syrup into water until combined, run SLUSH.",
  },
  {
    id: "flavored-extract-slush-builder",
    name: "Flavored Extract Slush (Build Your Own)",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing"],
    ingredients: [
      "10–30 ml extract (coconut, lemon, lime, orange, root beer, or strawberry)",
      "50–135 g granulated sugar",
      "720 ml–1.9 L water",
      "food coloring (optional)",
    ],
    directions: "Dissolve sugar and extract into the water, run SLUSH.",
  },
  {
    id: "caramel-milkshake-builder",
    name: "Caramel Milkshake (Build Your Own)",
    preset: "MILKSHAKE",
    source: "official",
    tags: ["creamy", "milkshake"],
    ingredients: [
      "480 ml–1.04 L milk",
      "240–560 ml heavy cream",
      "5–15 ml vanilla extract",
      "24–65 g granulated sugar",
      "60–160 ml caramel syrup",
    ],
    directions: "Whisk to combine, pour in (720 ml min), run MILKSHAKE.",
  },
  {
    id: "coffee-milkshake-builder",
    name: "Coffee Milkshake (Build Your Own)",
    preset: "MILKSHAKE",
    source: "official",
    tags: ["creamy", "milkshake", "coffee"],
    ingredients: [
      "480 ml–1.04 L milk",
      "240–560 ml heavy cream",
      "5–15 ml vanilla extract",
      "24–65 g granulated sugar",
      "60–160 ml coffee syrup",
    ],
    directions: "Whisk to combine, pour in (720 ml min), run MILKSHAKE.",
  },
  {
    id: "hot-cocoa-milkshake-builder",
    name: "Hot Cocoa Milkshake (Build Your Own)",
    preset: "MILKSHAKE",
    source: "official",
    tags: ["creamy", "milkshake", "chocolate"],
    ingredients: ["80–200 g hot cocoa powder mix", "600 ml–1.6 L milk", "120–320 ml heavy cream"],
    directions: "Whisk powder into milk and cream until dissolved, run MILKSHAKE.",
  },
  {
    id: "cape-codder-builder",
    name: "Cape Codder (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "fruity", "refreshing"],
    ingredients: ["600 ml–1.6 L cranberry juice", "120–300 ml vodka"],
    directions: "Combine base and alcohol, run SPIKED SLUSH.",
  },
  {
    id: "bellini-builder",
    name: "Bellini (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "fruity"],
    ingredients: ["600 ml–1.6 L peach nectar", "120–300 ml Champagne"],
    directions: "Combine base and alcohol, run SPIKED SLUSH.",
  },
  {
    id: "screwdriver-builder",
    name: "Screwdriver (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "citrus"],
    ingredients: ["600 ml–1.6 L orange juice", "120–300 ml vodka"],
    directions: "Combine base and alcohol, run SPIKED SLUSH.",
  },
  {
    id: "greyhound-builder",
    name: "Greyhound (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "citrus"],
    ingredients: ["600 ml–1.6 L grapefruit juice", "120–300 ml gin"],
    directions: "Combine base and alcohol, run SPIKED SLUSH.",
  },
  {
    id: "bloody-mary-builder",
    name: "Bloody Mary (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "spicy"],
    ingredients: ["600 ml–1.6 L tomato juice", "120–300 ml vodka"],
    directions: "Combine base and alcohol, run SPIKED SLUSH.",
  },
  {
    id: "cinnamon-whiskey-cider-builder",
    name: "Cinnamon Whiskey Cider (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "spicy", "fruity"],
    ingredients: ["600 ml–1.6 L apple cider", "120–300 ml cinnamon whiskey"],
    directions: "Combine base and alcohol, run SPIKED SLUSH.",
  },
  {
    id: "paloma-builder",
    name: "Paloma (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "citrus", "refreshing"],
    ingredients: ["600 ml–1.6 L grapefruit soda", "120–300 ml tequila"],
    directions: "Combine base and alcohol, run SPIKED SLUSH.",
  },
  {
    id: "whiskey-ginger-builder",
    name: "Whiskey & Ginger (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "spicy"],
    ingredients: ["600 ml–1.6 L ginger ale", "120–300 ml whiskey"],
    directions: "Combine base and alcohol, run SPIKED SLUSH.",
  },
  {
    id: "spiked-lemonade-builder",
    name: "Spiked Lemonade (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "citrus", "refreshing"],
    ingredients: ["600 ml–1.6 L lemonade", "120–300 ml vodka"],
    directions: "Combine base and alcohol, run SPIKED SLUSH.",
  },
  {
    id: "dark-and-stormy-builder",
    name: "Dark & Stormy (Build Your Own)",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "spicy", "refreshing"],
    ingredients: ["600 ml–1.6 L ginger beer", "120–300 ml dark rum"],
    directions: "Combine base and alcohol, run SPIKED SLUSH.",
  },

  // ---------- Additional community recipes (r/ninjaslushi) ----------
  // Close duplicates of recipes already above are intentionally left out —
  // e.g. Nick's classic scratch margarita (near-identical to the "Awesome"
  // scratch margarita below), the from-mix piña colada (near-identical to
  // the spiked piña colada above), Spiced Rum & Coke (near-identical to
  // Crown & Coke), and the caramel iced capp (near-identical to Iced Capp).
  {
    id: "limeade-concentrate-margarita",
    name: "Limeade-Concentrate Margarita",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "citrus", "fruity"],
    ingredients: [
      "1 can frozen limeade concentrate",
      "3 cans water",
      "1 can tequila",
      "⅓ can triple sec",
      "~120 ml strawberry purée (optional)",
    ],
    directions: "Combine and run SPIKED SLUSH. Batches well in jugs for the freezer.",
    url: "https://reddit.com/r/ninjaslushi/comments/1iv4fi9/our_favorite_frozen_margs/",
  },
  {
    id: "awesome-scratch-margarita",
    name: "\"Awesome\" Scratch Margarita",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "citrus"],
    ingredients: [
      "345 ml tequila",
      "175 ml orange liqueur (triple sec or Cointreau)",
      "225 ml rich simple syrup (2:1 sugar:water)",
      "265 ml lime juice",
      "920 ml water",
    ],
    directions: "Combine and run SPIKED SLUSH. Dialed to Brix 13.5% / ABV 10.8% for a 1.9 L batch.",
  },
  {
    id: "low-cal-pink-cadillac-margarita",
    name: "Low-Cal Pink Cadillac Margarita",
    preset: "SLUSH",
    source: "community",
    tags: ["cocktail", "citrus", "refreshing"],
    ingredients: ["1 can Fresca", "1 shot silver tequila", "30 ml grenadine"],
    directions: "Combine and run SLUSH at 4 bars.",
    url: "https://reddit.com/r/ninjaslushi/comments/1i8znfj/low_cal_pink_cadillac_marg/",
  },
  {
    id: "gelatin-stabilized-frose",
    name: "Gelatin-Stabilized Frosé",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "fruity"],
    ingredients: [
      "1 bottle rosé wine",
      "120 ml vodka",
      "240 ml Peachtree schnapps",
      "~10 fresh strawberries, puréed",
      "~18–24 g monk fruit sweetener",
      "~3 g unflavored gelatin (dissolved in warm, not hot, liquid)",
    ],
    directions:
      "Dissolve gelatin in warm liquid, purée with the strawberries, combine with everything else, run SPIKED SLUSH. Makes ~1.5 L.",
    difficultyOverride: "advanced",
    url: "https://reddit.com/r/ninjaslushi/comments/1klb4f8/may_have_cracked_the_frose/",
  },
  {
    id: "strawberry-frose-freeform",
    name: "Strawberry Frosé (Freeform)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "fruity"],
    ingredients: [
      "1 bottle Kim Crawford rosé",
      "240 ml lemonade",
      "juice of 1 lemon",
      "juice of 1 lime",
      "puréed strawberries with sugar, to taste",
      "30–60 ml passionfruit Cîroc",
    ],
    directions: "Purée the strawberries with sugar, combine everything, run SPIKED SLUSH.",
  },
  {
    id: "almost-bahama-mama",
    name: "(Almost) Bahama Mama",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "tropical", "fruity"],
    ingredients: [
      "300 ml coconut fat-washed rum",
      "150 ml banana liqueur",
      "480 ml pineapple juice",
      "120 ml ginger syrup",
      "360 ml water",
      "480 ml orange juice",
    ],
    directions: "Combine and run SPIKED SLUSH. Garnish glass with a grenadine swirl.",
    url: "https://reddit.com/r/ninjaslushi/comments/1i52z13/almost_bahama_mama_slushie/",
  },
  {
    id: "john-daley",
    name: "John Daley",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "refreshing", "citrus"],
    ingredients: ["2 cans Arnold Palmer (345 ml each)", "135 ml Tito's vodka"],
    directions: "Combine and run SPIKED SLUSH.",
  },
  {
    id: "electric-lemonade",
    name: "Electric Lemonade",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "citrus", "refreshing"],
    ingredients: [
      "960 ml real-sugar lemonade",
      "240 ml Tito's vodka",
      "simple syrup, to sweeten",
      "blue curaçao (poured in the bottom of the glass)",
    ],
    directions: "Combine lemonade, vodka, and simple syrup; run SPIKED SLUSH. Pour over blue curaçao in the glass.",
  },
  {
    id: "grey-goose-fanta",
    name: "Grey Goose Fanta",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "citrus"],
    ingredients: ["¼ bottle Grey Goose vodka", "1.5 L Fanta lemon", "100 ml Robinsons lemon squash", "50 ml blue agave syrup"],
    directions: "Combine and run SPIKED SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1h2tvkj/just_got_my_nina_slushi/",
  },
  {
    id: "jets-in-7",
    name: "The Jets in 7",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail"],
    ingredients: [
      "equal parts Smirnoff Ice and 7Up",
      "90–210 ml Crown Royal",
      "1 White Monster energy drink",
      "60 ml blue curaçao (topper)",
    ],
    directions: "Combine Smirnoff Ice, 7Up, Crown Royal, and Monster; run SPIKED SLUSH. Top with blue curaçao.",
    url: "https://reddit.com/r/ninjaslushi/comments/1kf1zu3/my_new_playoff_favorite_the_jets_in_7/",
  },
  {
    id: "five-spirit-frozen-cocktail",
    name: "\"My Favorite\" 5-Spirit Cocktail",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "citrus"],
    ingredients: [
      "40 ml gin",
      "40 ml vodka",
      "40 ml triple sec",
      "40 ml tequila",
      "40 ml white rum",
      "40 ml Monin blue curaçao syrup",
      "30 ml lemon juice",
      "30 ml lime juice",
      "1 L Sprite",
    ],
    directions: "Combine all spirits, syrup, juices, and Sprite; run SPIKED SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1ke2imq/my_very_favorite_frozen_cocktail/",
  },
  {
    id: "squirt-cherry-limeade-punch",
    name: "Squirt Cherry-Limeade Punch",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "fruity", "citrus", "refreshing"],
    ingredients: ["1×2 L Squirt (grapefruit soda)", "2 packets Sonic Cherry Limeade zero-sugar drink mix", "480 ml vodka"],
    directions: "Combine and run SPIKED SLUSH.",
  },
  {
    id: "margarita-man-tko",
    name: "Margarita Man TKO (Tropical Knockout)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "tropical", "fruity"],
    ingredients: ["1.35 L water", "270 ml Margarita Man Tropical Knockout mix", "285 ml rum or vodka"],
    directions: "Combine and run SPIKED SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1f7epse/i_made_margarita_mans_tko_tropical_knockout/",
  },
  {
    id: "mr-cool-it-slush-syrup",
    name: "Slush Syrup (UK, Mr Cool It)",
    preset: "SLUSH",
    source: "community",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: ["270 ml Mr Cool It slush syrup", "water, to the fill line"],
    directions: "Pour syrup in, top up with water to the fill line, run SLUSH at freeze setting 4.",
  },
  {
    id: "sugar-free-strawberry-lemonade",
    name: "Sugar-Free Strawberry Lemonade Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing", "fruity", "citrus"],
    ingredients: ["1.44 L strawberry lemonade (unsweetened/diet base)", "200 g granulated allulose"],
    directions: "Stir allulose in until dissolved, run SLUSH.",
    sugarFreeNote: "Already built around allulose as the sole sweetener — the reference build the sugar-free toggle emulates for other recipes.",
  },
  {
    id: "splenda-magic-baker-soda-slush",
    name: "Splenda \"Magic Baker\" Sugar-Free Soda Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing"],
    ingredients: ["1 can diet/zero-sugar soda (e.g. Sparkling Ice, Baja Blast Zero)", "~12 g Splenda \"Magic Baker\" allulose per 355 ml can"],
    directions: "Stir allulose into the soda until dissolved, run SLUSH.",
    sugarFreeNote: "Already the sugar-free build — this is the same pattern the toggle applies automatically to other diet sodas.",
  },
  {
    id: "thc-lemonade",
    name: "THC Lemonade",
    preset: "SLUSH",
    source: "community",
    tags: ["fruity", "citrus", "refreshing"],
    ingredients: ["4 cans (960 ml) Cann Pineapple-Jalapeño THC drink", "960 ml Chick-fil-A lemonade, strained"],
    directions:
      "Combine roughly 1:1 and run SLUSH. Cannabis-infused — check local legality and dose according to the THC beverage's label.",
    url: "https://reddit.com/r/ninjaslushi/comments/1i54i0s/thc_lemonade/",
  },
];

// Merge any `tagsExtra` / `tagsMocktail` shorthand into the main tags array
// so every recipe object downstream only needs to read `.tags`.
RECIPES.forEach((r) => {
  if (r.tagsExtra) {
    r.tags = r.tags.concat(r.tagsExtra);
    delete r.tagsExtra;
  }
  if (r.tagsMocktail) {
    r.tags = r.tags.concat(["mocktail"]);
    delete r.tagsMocktail;
  }
});
