/*
 * Ninja Slushi recipe dataset.
 *
 * Curated from ../references/official-recipes.md, ../references/recipes.md
 * and ../references/community-recipes.md.
 *
 * Each recipe:
 *   id           unique slug
 *   name         display name
 *   preset       one of SLUSH | SPIKED SLUSH | FROZEN JUICE | MILKSHAKE | FRAPPE
 *   source       "official" (Ninja Inspiration Guide) or "community" (r/ninjaslushi)
 *   tags         array drawn from CATEGORY_TAGS below — a recipe can have several
 *   difficulty   "easy" | "medium" | "advanced" (see computeDifficulty() in app.js
 *                for the rule; a few recipes pin it explicitly via `difficultyOverride`
 *                when ingredient count alone would understate the effort, e.g. a
 *                gelatin-stabilized frosé)
 * kid           optional, true for kid-friendly recipes
 *   ingredients  array of free-text "qty + ingredient" strings (this is what the
 *                sugar-free rewriter in app.js pattern-matches against)
 *   directions   short prep/run notes
 *   sugarFreeNote  optional recipe-specific note shown in sugar-free mode, in
 *                addition to the automatic per-ingredient rewrite
 *   url          optional source link (community recipes only)
 */

const CATEGORY_TAGS = [
  "creamy", "milkshake", "refreshing", "fruity", "spicy",
  "tropical", "citrus", "coffee", "chocolate", "cocktail", "mocktail",
];

const RECIPES = [
  // ---------- SLUSH ----------
  {
    id: "one-ingredient-soda-slush",
    name: "One-Ingredient Soda Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: ["2–5 (355 ml) cans any regular full-sugar soda"],
    directions: "Pour soda into the vessel. Run SLUSH (~3 bars). Diet/sugar-free soda will not work on its own.",
    sugarFreeNote: "Diet soda alone will not freeze. Use a diet/zero-sugar soda and add ~15–22 ml liquid allulose (or ~12–18 g granulated) per 355 ml can to restore the sugar the machine needs.",
  },
  {
    id: "pink-lemonade-slush",
    name: "Pink Lemonade Slush",
    preset: "SLUSH",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "citrus"],
    ingredients: ["660 ml–1.76 L water", "45–105 g pink lemonade powder mix"],
    directions: "Whisk powder into water until fully dissolved, pour in, run SLUSH.",
  },
  {
    id: "sodas-that-just-work",
    name: "Classic Soda Slush (Coke / Root Beer / Fanta / Pepsi / Mountain Dew)",
    preset: "SLUSH",
    source: "community",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: ["1.9 L any full-sugar soda (Coke, root beer, strawberry Fanta, cherry Coke, Pepsi, Mountain Dew, Jarritos)"],
    directions: "Run SLUSH at ~3 bars. More flavorful sodas work better — freezing mutes flavor. Avoid beer.",
  },
  {
    id: "cherry-icee-copycat",
    name: "Cherry Icee Copycat",
    preset: "SLUSH",
    source: "community",
    kid: true,
    tags: ["refreshing", "fruity"],
    ingredients: ["3 parts full-sugar Sprite", "1 part Hawaiian Shaved Ice Classic Cherry syrup"],
    directions: "Mix and run SLUSH. Must use full-sugar Sprite, not Zero.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hnpzto/getting_closer_to_a_cherry_icee/",
  },
  {
    id: "icee-from-syrup",
    name: "Icee From Syrup",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing", "fruity"],
    ingredients: ["180 ml Icee syrup (≈22 g sugar)", "840 ml water"],
    directions: "Low sugar (~2%) — run SLUSH +2 to +3 bars for a proper thick slush.",
  },
  {
    id: "orange-creamsicle",
    name: "Orange Creamsicle Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["creamy", "fruity", "citrus"],
    ingredients: ["2 L orange soda", "dash vanilla extract", "½ can sweetened condensed milk"],
    directions: "Mix and run SLUSH. Tastes like a Creamsicle.",
  },
  {
    id: "pink-starburst-slush",
    name: "Pink Starburst Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["creamy", "fruity"],
    ingredients: ["1 bottle Simply Watermelon juice", "½ can sweetened condensed milk"],
    directions: "Mix well before pouring in. Run SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jbhaf3/pink_starburst_slush/",
  },
  {
    id: "triple-dr-pepper",
    name: "Triple Dr Pepper Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing", "fruity"],
    ingredients: ["1 can Dr Pepper Strawberries & Cream", "1 can Dr Pepper Creamy Coconut", "1 can regular Dr Pepper"],
    directions: "Combine all three and run SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1igvgj5/my_favourite_slush/",
  },
  {
    id: "orange-julius",
    name: "Orange Julius Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["creamy", "citrus", "fruity"],
    ingredients: ["1.44 L orange juice (no pulp)", "480 ml 2% milk", "15 ml vanilla extract", "~200 g granulated sugar (or allulose)"],
    directions: "Whisk, pour in, run SLUSH at 6 bars.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hsfbgx/orange_julius/",
  },
  {
    id: "zevia-allulose-slush",
    name: "Sugar-Free Zevia Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing"],
    ingredients: ["1 can Zevia (unsweetened soda)", "~22 ml liquid allulose per can", "few drops food coloring (optional, Zevia is clear)"],
    directions: "Stir allulose into the Zevia until dissolved, then run SLUSH.",
    sugarFreeNote: "Already the sugar-free reference build — this is what the toggle is emulating for other sodas.",
  },
  {
    id: "coke-zero-slush",
    name: "Sugar-Free Coke Zero Slush",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing"],
    ingredients: ["2 cans Coke Zero", "~50 g Splenda allulose", "~50 g monk fruit-erythritol blend"],
    directions: "Aim for real Coke's ~39 g sugar equivalent. Run SLUSH, maybe +1 bar.",
  },
  {
    id: "half-diet-blend",
    name: "Half-Diet Soda Blend",
    preset: "SLUSH",
    source: "community",
    tags: ["refreshing", "fruity"],
    ingredients: ["¼ full-sugar Orange Crush", "¾ Sprite Zero (or ½ regular soda + ½ diet soda)"],
    directions: "Combine and run SLUSH — slushes fine with reduced total sugar.",
  },

  // ---------- FROZEN JUICE ----------
  {
    id: "cranberry-lime-slush",
    name: "Cranberry Lime Slush",
    preset: "FROZEN JUICE",
    source: "official",
    kid: true,
    tags: ["refreshing", "fruity", "citrus"],
    ingredients: ["560 ml–1.38 L cranberry juice", "160–360 ml limeade"],
    directions: "Pour both in and run FROZEN JUICE.",
  },
  {
    id: "tropical-juice-slush",
    name: "Tropical Juice Slush",
    preset: "FROZEN JUICE",
    source: "official",
    kid: true,
    tags: ["tropical", "fruity", "refreshing"],
    ingredients: ["720 ml–1.8 L tropical juice blend"],
    directions: "Pour in and run FROZEN JUICE.",
  },
  {
    id: "straight-single-juices",
    name: "Straight Single-Juice Slush (Mango / Lemonade / Fruit Punch)",
    preset: "FROZEN JUICE",
    source: "community",
    kid: true,
    tags: ["fruity", "refreshing", "tropical"],
    ingredients: ["1.9 L single juice: Snapple Mango Madness, Simply Lemonade, Snapple Fruit Punch, orange juice, or apple cider"],
    directions: "Run FROZEN JUICE (or SLUSH) at a low bar. Tart/low-sugar juices may need added sugar. Apple juice (Mott's) needs +2 bars.",
  },
  {
    id: "caramel-apple-slush",
    name: "Caramel Apple Slush",
    preset: "FROZEN JUICE",
    source: "community",
    kid: true,
    tags: ["fruity", "creamy"],
    ingredients: ["1.9 L apple cider", "caramel syrup (for swirl)", "whipped cream + cinnamon (topping)"],
    directions: "Run apple cider on FROZEN JUICE at 2 bars; swirl the glass with caramel syrup, top with whipped cream and cinnamon.",
  },
  {
    id: "fall-pumpkin-cider-kids",
    name: "Fall Pumpkin Cider (Kids)",
    preset: "FROZEN JUICE",
    source: "community",
    kid: true,
    tags: ["spicy", "fruity"],
    ingredients: ["2 L apple cider", "½ can (of 425 g) pumpkin purée", "50 g brown sugar", "50 g white sugar", "~2 g pumpkin pie spice", "5 ml vanilla extract"],
    directions: "Whisk pumpkin purée and spices into cider, then run FROZEN JUICE.",
  },
  {
    id: "lemonade-cranberry-mocktail",
    name: "Non-Alcoholic Lemonade-Cranberry Slush",
    preset: "FROZEN JUICE",
    source: "community",
    tags: ["mocktail", "citrus", "refreshing"],
    ingredients: ["480 ml lemonade", "240 ml cranberry juice", "splash simple syrup"],
    directions: "Mix and run FROZEN JUICE/SLUSH. Add 120 ml vodka for the adult version.",
  },

  // ---------- MILKSHAKE ----------
  {
    id: "vanilla-milkshake",
    name: "Vanilla Milkshake",
    preset: "MILKSHAKE",
    source: "official",
    kid: true,
    tags: ["creamy", "milkshake"],
    ingredients: ["600 ml–1.38 L whole milk", "120–270 ml heavy cream", "100–250 g granulated sugar", "15–40 ml vanilla extract"],
    directions: "Whisk to combine, pour in (720 ml min), run MILKSHAKE. Dispense within 30 minutes.",
  },
  {
    id: "chocolate-milkshake",
    name: "Chocolate Milkshake",
    preset: "MILKSHAKE",
    source: "official",
    kid: true,
    tags: ["creamy", "milkshake", "chocolate"],
    ingredients: ["480 ml–1.04 L whole milk", "240–560 ml heavy cream", "5–15 ml vanilla extract", "24–65 g granulated sugar", "60–160 ml chocolate syrup", "10–43 g cocoa powder"],
    directions: "Whisk until sugar/syrup/cocoa fully dissolved, pour in, run MILKSHAKE. Optional: whipped cream, chocolate sauce.",
  },
  {
    id: "wendys-frosty-copycat",
    name: "Wendy's Frosty Copycat",
    preset: "MILKSHAKE",
    source: "community",
    kid: true,
    tags: ["creamy", "milkshake", "chocolate"],
    ingredients: ["1.2 L 2% chocolate milk", "1 can (420 ml) sweetened condensed milk", "¾ container Cool Whip"],
    directions: "Whisk together first, then run MILKSHAKE +1 to +2 bars. Full 1.9 L batch ≈ 40 min.",
    url: "https://reddit.com/r/ninjaslushi/comments/1h8vw9q/ninja_slush_recipes_ongoing_list/",
  },
  {
    id: "halo-top-chocolate-shake",
    name: "Halo Top Chocolate Shake (Low-Cal)",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake", "chocolate"],
    ingredients: ["2 tubs (480 ml each) Halo Top chocolate, melted", "240 ml whole milk", "120 ml zero-sugar Cool Whip"],
    directions: "Melt Halo Top, whisk everything together, run MILKSHAKE. Add Bailey's for a low-cal mudslide.",
    url: "https://reddit.com/r/ninjaslushi/comments/1k0um84/halo_top_milkshake/",
  },
  {
    id: "protein-frosty",
    name: "Protein \"Frosty\"",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake", "chocolate"],
    ingredients: ["960 ml chocolate milk", "960 ml lactose-free milk", "1 packet Carnation Instant Breakfast", "120 ml sweetened condensed milk", "whipped cream (3-sec squirt, for fluff)"],
    directions: "Whisk together and run MILKSHAKE.",
  },
  {
    id: "strawberry-milkshake",
    name: "Strawberry Milkshake",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake", "fruity"],
    ingredients: ["800 ml milk", "50 ml strawberry syrup", "1.5 capfuls vanilla extract", "100 ml double cream", "200 ml sweetened condensed milk"],
    directions: "Whisk to combine, run MILKSHAKE. Halve the sweetener for less-sweet US palates.",
    url: "https://reddit.com/r/ninjaslushi/comments/1h45jvt/just_made_my_first_strawberry_milkshake/",
    difficultyOverride: "medium",
  },
  {
    id: "creme-brulee-milkshake",
    name: "Crème Brûlée Milkshake",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake"],
    ingredients: ["600 ml whole milk", "100 ml heavy cream", "120 ml+ Monin crème brûlée syrup"],
    directions: "Whisk together, run MILKSHAKE.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jkhws1/milkshake_go%C3%BBt_cr%C3%A8me_br%C3%BBl%C3%A9e/",
  },
  {
    id: "dole-whip-from-mix",
    name: "Dole Whip (From Mix)",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake", "tropical", "fruity"],
    ingredients: ["~120 g Dole Whip mix (check package)", "960 ml cold water", "splash heavy whipping cream (optional)"],
    directions: "Whisk mix into water, run MILKSHAKE +1.",
    url: "https://reddit.com/r/ninjaslushi/comments/1ka00cw/dole_whip/",
  },
  {
    id: "dole-whip-from-scratch",
    name: "Dole Whip Shake (From Scratch)",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake", "tropical", "fruity"],
    ingredients: ["2×180 ml pineapple juice", "2 ripe bananas", "1 can coconut milk", "~8 g powdered sugar", "15 ml lime juice"],
    directions: "Blend the fruit first, then run MILKSHAKE. Makes ~1.4 L.",
    difficultyOverride: "advanced",
  },
  {
    id: "dairy-free-pb-shake",
    name: "Dairy-Free Peanut Butter Shake",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["creamy", "milkshake"],
    ingredients: ["oat milk", "plant-based heavy cream", "sugar (to taste)", "PB2 powder", "a little peanut-butter syrup"],
    directions: "Amounts are vague in the source — use as a template and adjust to taste. Run MILKSHAKE.",
  },

  // ---------- FRAPPE ----------
  {
    id: "coffee-frappe",
    name: "Coffee Frappé",
    preset: "FRAPPE",
    source: "official",
    tags: ["coffee", "creamy"],
    ingredients: ["240–540 ml half & half", "480 ml–1.08 L black coffee", "5–15 ml vanilla extract", "65–150 g granulated sugar"],
    directions: "Whisk to combine, pour in (720 ml min), run FRAPPÉ. Dispense within 30 minutes.",
  },
  {
    id: "caramel-frappe",
    name: "Caramel Frappé",
    preset: "FRAPPE",
    source: "official",
    tags: ["coffee", "creamy"],
    ingredients: ["240–540 ml half & half", "480 ml–1.08 L black coffee", "80–180 ml caramel sauce"],
    directions: "Whisk, pour in, run FRAPPÉ. Swap caramel sauce for chocolate sauce for a Mocha Frappé.",
    tagsExtra: ["chocolate"],
  },
  {
    id: "starbucks-bottle-frappe",
    name: "Vanilla-Caramel Frappé (Bottled Starbucks)",
    preset: "FRAPPE",
    source: "community",
    tags: ["coffee", "creamy"],
    ingredients: ["480 ml Vanilla Starbucks Frappuccino", "180 ml Caramel Starbucks Frappuccino", "30 ml heavy whipping cream"],
    directions: "Combine and run FRAPPÉ at 3 bars, ~20 min. Rim with caramel + Biscoff for a treat.",
    url: "https://reddit.com/r/ninjaslushi/comments/1i66579/vanilla_caramel_frapp%C3%A9_with_a_chocolate_and/",
  },
  {
    id: "caramel-frap-from-scratch",
    name: "Caramel Frap (From Scratch)",
    preset: "FRAPPE",
    source: "community",
    tags: ["coffee", "creamy"],
    ingredients: ["720 ml chilled black coffee", "720 ml chilled whole milk", "60 ml heavy cream", "200 g caster sugar"],
    directions: "Whisk until sugar dissolves. Run FRAPPÉ, ~40 min. Line the cup with caramel sauce.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jjvqtg/made_the_wife_a_caramel_frap_today_and/",
  },
  {
    id: "low-cal-nondairy-coffee-frappe",
    name: "Low-Cal Non-Dairy Coffee Frappé",
    preset: "MILKSHAKE",
    source: "community",
    tags: ["coffee"],
    ingredients: ["660 ml coffee", "15 ml vanilla extract", "~96 g granular allulose", "900 ml unsweetened almond milk"],
    directions: "Whisk together and run on MILKSHAKE (not FRAPPÉ). Icy due to no dairy, but tasty.",
    url: "https://reddit.com/r/ninjaslushi/comments/1k8p4an/coffee_frappe_low_cal_nondairy/",
    sugarFreeNote: "Already built with allulose — the reference build for the sugar-free toggle.",
  },
  {
    id: "iced-capp",
    name: "Iced Capp",
    preset: "FRAPPE",
    source: "community",
    tags: ["coffee", "creamy"],
    ingredients: ["480 ml hot water", "~8 g instant coffee", "240 ml 10% cream (half-and-half)", "50 g granulated sugar", "5 ml vanilla extract"],
    directions: "Dissolve coffee/sugar in the hot water, cool, add cream + vanilla. Run FRAPPÉ −1 bar, ready in 10–15 min.",
  },

  // ---------- SPIKED SLUSH ----------
  {
    id: "frozen-mimosa",
    name: "Frozen Mimosa",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "fruity", "citrus"],
    ingredients: ["300–800 ml orange juice", "420 ml–1.12 L sparkling wine / Champagne / Prosecco / Cava"],
    directions: "Pour both in, run SPIKED SLUSH. Mocktail: swap sparkling wine for sparkling white grape juice/cider, run SLUSH at 8 bars.",
    tagsMocktail: true,
  },
  {
    id: "coconut-lime-daiquiri",
    name: "Coconut Lime Daiquiri",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "tropical", "citrus", "creamy"],
    ingredients: ["300–800 ml unsweetened canned coconut milk", "300–800 ml limeade", "90–240 ml light rum", "juice of 2–4 fresh limes", "36–65 g granulated sugar"],
    directions: "Whisk until coconut milk is emulsified and smooth, pour in, run SPIKED SLUSH. Mocktail: zero-proof rum on SLUSH.",
  },
  {
    id: "frose-official",
    name: "Frosé",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "fruity"],
    ingredients: ["510 ml–1.04 L rosé wine", "270–720 ml white cranberry-strawberry juice", "60–160 ml simple syrup"],
    directions: "Combine, run SPIKED SLUSH at 8 bars. Optional garnish: strawberries.",
  },
  {
    id: "red-sangria",
    name: "Red Sangria",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "fruity", "citrus"],
    ingredients: ["300–780 ml red wine", "40–120 ml orange liqueur or brandy", "360–900 ml orange juice", "18–50 g light brown sugar"],
    directions: "Combine, run SPIKED SLUSH. Optional garnish: orange slices.",
  },
  {
    id: "frozen-mango-margarita",
    name: "Frozen Mango Margarita",
    preset: "SPIKED SLUSH",
    source: "official",
    tags: ["cocktail", "fruity", "tropical", "citrus"],
    ingredients: ["480 ml–1.2 L mango margarita mix", "80–180 ml water", "80–180 ml lime juice", "80–180 ml tequila"],
    directions: "Pour all in, run SPIKED SLUSH. Mocktail: swap tequila for zero-proof tequila, run SLUSH at 5 bars.",
  },
  {
    id: "cinco-de-mayo-grapefruit-marg",
    name: "Cinco de Mayo Grapefruit Margarita",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "citrus", "fruity"],
    ingredients: ["360 ml reposado tequila", "960 ml margarita mix", "300 ml fresh grapefruit juice", "120 ml fresh lime juice", "360 ml water"],
    directions: "Combine, run SPIKED SLUSH at 10 bars. A Chambord floater on top is a nice touch.",
    url: "https://reddit.com/r/ninjaslushi/comments/1kfhntm/in_honor_of_cinco_de_mayo/",
  },
  {
    id: "skinny-margarita-allulose",
    name: "Skinny Margarita (Allulose)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "citrus"],
    ingredients: ["192 ml fresh lime juice", "280 ml blanco tequila", "152 ml Cointreau", "46 ml liquid allulose", "710 ml water"],
    directions: "Combine, run SPIKED SLUSH +1 bar. Nearly fills the larger tank.",
    url: "https://reddit.com/r/ninjaslushi/comments/1i8znfj/low_cal_pink_cadillac_marg/",
    sugarFreeNote: "Already built with allulose — no conversion needed.",
  },
  {
    id: "pina-colada-spiked",
    name: "Piña Colada (Spiked)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "tropical", "creamy"],
    ingredients: ["540 ml pineapple (3 small cans)", "1 small can (120 ml) cream of coconut", "150 ml sweetened condensed milk", "30 ml lime juice", "115 ml dark rum"],
    directions: "Refrigerate ingredients first, then run SPIKED SLUSH. Adjust sweetness before pouring in.",
    url: "https://reddit.com/r/ninjaslushi/comments/1esnato/pina_colada/",
  },
  {
    id: "painkiller",
    name: "Painkiller",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "tropical", "spicy"],
    ingredients: ["600 ml pineapple juice", "300 ml orange juice", "300–360 ml cream of coconut (microwaved 60 s to liquefy)", "180–480 ml Myers/navy-strength rum", "grated nutmeg (topping)"],
    directions: "Combine, run SPIKED SLUSH at the coldest setting. Add water if too thin; grate nutmeg on top.",
    url: "https://reddit.com/r/ninjaslushi/comments/1j0g7ci/what_setting_for_a_mudslide/",
  },
  {
    id: "bushwacker",
    name: "Bushwacker (Flora-Bama Copycat)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "creamy", "chocolate", "tropical"],
    ingredients: ["120 ml Cruzan aged dark rum", "120 ml vodka", "120 ml Amaretto", "120 ml Irish cream", "120 ml Kahlúa", "120 ml crème de cacao", "120 ml cream of coconut", "480 ml Fairlife 2% milk", "240 ml water"],
    directions: "Pre-mix minus the cream of coconut and freeze for a party; add cream of coconut per refill. Run SPIKED SLUSH.",
    difficultyOverride: "advanced",
  },
  {
    id: "paralyzer",
    name: "Paralyzer",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "creamy", "chocolate"],
    ingredients: ["720 ml milk", "1 can cola", "120 ml vodka", "180 ml Kahlúa"],
    directions: "Combine, run SPIKED SLUSH ~25 min. Tip: swap milk for water + 18% cream for a lighter-yet-richer result.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hq1c26/paralyzer_slush/",
  },
  {
    id: "ninja-hummer",
    name: "Ninja Hummer",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "creamy", "chocolate"],
    ingredients: ["960 ml heavy cream", "480 ml milk", "180 ml vodka", "180 ml Mr. Black (or Kahlúa)", "200 g granulated sugar"],
    directions: "Combine, run SPIKED SLUSH. Top with whipped cream + dark chocolate syrup.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hs3jj6/ninja_hummer/",
  },
  {
    id: "boozy-eggnog-milkshake",
    name: "Boozy Eggnog Milkshake",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "creamy", "spicy"],
    ingredients: ["960 ml eggnog", "60 ml water", "240 ml whole milk", "360 ml Irish whiskey"],
    directions: "Combine and run SPIKED SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hre0zo/boozy_egg_nog_milkshake/",
  },
  {
    id: "hard-cider-slush",
    name: "Hard Cider Slush",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "spicy", "fruity"],
    ingredients: ["1.44 L real apple cider (not juice)", "4 shots Bulleit bourbon (or Crown Royal)"],
    directions: "Combine and run SPIKED SLUSH. Better cider makes a better result.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jnk792/hard_cider_slush/",
  },
  {
    id: "london-mule",
    name: "London Mule",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "citrus", "spicy", "refreshing"],
    ingredients: ["180 ml gin", "60 ml lime juice", "540 ml diet ginger beer", "6 dashes bitters"],
    directions: "Chill and mix first (~30 min), then run SPIKED SLUSH, no adjustments needed.",
    url: "https://reddit.com/r/ninjaslushi/comments/1h8vw9q/ninja_slush_recipes_ongoing_list/",
    sugarFreeNote: "Already uses diet ginger beer — the alcohol acts as the antifreeze here, so no added sugar is needed.",
  },
  {
    id: "frozen-green-tea-shot",
    name: "Frozen Green Tea Shot",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "fruity", "spicy"],
    ingredients: ["240 ml Jameson", "240 ml peach schnapps", "360 ml sour mix", "480 ml Sprite", "water, to fill/adjust"],
    directions: "Combine and run SPIKED SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jdj2np/any_st_patrick_slushy_ideas/",
  },
  {
    id: "liquid-marijuana",
    name: "Liquid Marijuana",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "tropical", "fruity"],
    ingredients: ["60 ml Malibu Black", "60 ml melon liqueur", "60 ml blue curaçao", "60 ml spiced rum", "480 ml pineapple juice", "240 ml 7Up", "360 ml water"],
    directions: "Combine and run SPIKED SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jdj2np/any_st_patrick_slushy_ideas/",
    difficultyOverride: "advanced",
  },
  {
    id: "irish-coffee-frappe",
    name: "Irish Coffee Frappé",
    preset: "FRAPPE",
    source: "community",
    tags: ["cocktail", "coffee", "creamy"],
    ingredients: ["Jameson (to taste)", "espresso (to taste)", "Irish cream (to taste)", "half-and-half (to taste)", "vanilla extract (to taste)", "a little sugar (to taste)"],
    directions: "Amounts to taste — combine and run FRAPPÉ.",
    url: "https://reddit.com/r/ninjaslushi/comments/1jdj2np/any_st_patrick_slushy_ideas/",
  },
  {
    id: "sugar-free-rum-punch",
    name: "Sugar-Free Rum Punch",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "fruity", "refreshing"],
    ingredients: ["1.56 L water", "360 ml Captain Morgan", "Crystal Light fruit punch mix, to the fill line", "a few squirts lime juice"],
    directions: "Combine, run SPIKED SLUSH −1 bar. The alcohol is the antifreeze, so no added sugar is needed.",
    url: "https://reddit.com/r/ninjaslushi/comments/1iwxto6/sugarfree_rum_punch/",
    sugarFreeNote: "Already sugar-free — built around Crystal Light + alcohol as the antifreeze.",
  },
  {
    id: "fall-pumpkin-cider-adult",
    name: "Fall Pumpkin Cider (Adult)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "spicy", "fruity"],
    ingredients: ["2 L apple cider", "½ can (of 425 g) pumpkin purée", "50 g brown sugar", "50 g white sugar", "~2 g pumpkin pie spice", "5 ml vanilla extract", "Fireball whisky, to taste"],
    directions: "Whisk pumpkin/spice into cider, add Fireball to taste, run SPIKED SLUSH.",
  },
  {
    id: "crown-and-coke",
    name: "Crown & Coke (Salt Grass Copycat)",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail"],
    ingredients: ["2 cans Coca-Cola (355 ml each)", "120 ml Crown Royal (vanilla Crown chaser optional)"],
    directions: "Combine and run SPIKED SLUSH.",
  },
  {
    id: "boozey-cherry-limeade",
    name: "Boozey Cherry Limeade",
    preset: "SPIKED SLUSH",
    source: "community",
    tags: ["cocktail", "fruity", "citrus", "refreshing"],
    ingredients: ["240 ml Deep Eddy lime vodka", "240 ml water", "1.44 L cherry 7Up"],
    directions: "Combine and run SPIKED SLUSH.",
    url: "https://reddit.com/r/ninjaslushi/comments/1hm6ebf/boozey_cherry_limeade/",
  },
];

// Merge any `tagsExtra` / `tagsMocktail` shorthand into the main tags array
// so every recipe object downstream only needs to read `.tags`.
RECIPES.forEach((r) => {
  if (r.tagsExtra) {
    r.tags = r.tags.concat(r.tagsExtra);
    delete r.tagsExtra;
  }
  if (r.tagsMocktail) {
    r.tags = r.tags.concat(["mocktail"]);
    delete r.tagsMocktail;
  }
});
